(()=>{
const $=id=>document.getElementById(id);const slides=window.FUNFARM_SLIDES||[];let db=null,current=0;const params=new URLSearchParams(location.search);const channel=(params.get('canal')||window.FUNFARM_DEFAULT_CHANNEL||'funfarm').replace(/[^a-zA-Z0-9_-]/g,'_');const root=window.FUNFARM_DB_ROOT||'funfarm_apresentacao/canais';const base=`${root}/${channel}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=i=>`<i class="fa-solid ${esc(i||'fa-leaf')}"></i>`;
function list(items){return `<div class="list">${(items||[]).map(x=>`<div class="item">${esc(x)}</div>`).join('')}</div>`}
function renderSlide(s){let h='';switch(s.type){
case'cover':h=`<section class="cover"><div class="kicker">${esc(s.kicker)}</div><h2 class="mega">${esc(s.title)}</h2><div class="cover-line"></div><div class="sub">${esc(s.subtitle)}</div><div class="line">${esc(s.line)}</div></section>`;break;
case'statement':h=`<section class="statement"><div class="big">${esc(s.big)}</div><div class="text">${esc(s.text)}</div><div class="tags">${(s.tags||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></section>`;break;
case'grid':h=`<section class="gridcards">${(s.cards||[]).map(c=>`<div class="card">${icon(c.i)}<h3>${esc(c.t)}</h3><p>${esc(c.d)}</p></div>`).join('')}</section>`;break;
case'beforeafter':h=`<section class="ba"><div class="panel bad"><div class="label">${esc(s.left.label)}</div><h3>${esc(s.left.title)}</h3>${list(s.left.items)}</div><div class="panel good"><div class="label">${esc(s.right.label)}</div><h3>${esc(s.right.title)}</h3>${list(s.right.items)}</div></section>`;break;
case'process':h=`<section class="process">${(s.steps||[]).map(x=>`<div class="step"><div class="n">${esc(x.n)}</div><h3>${esc(x.t)}</h3><p>${esc(x.d)}</p></div>`).join('')}</section>`;break;
case'risk5':h=`<section class="risk5">${(s.risks||[]).map(x=>`<div class="risk">${icon(x.i)}<h3>${esc(x.t)}</h3></div>`).join('')}</section>`;break;
case'scenario':h=`<section class="scenario"><div class="accent">${esc(s.accent)}</div><div class="question">${esc(s.question)}</div><div class="cols">${(s.columns||[]).map(c=>`<div class="panel"><h3>${esc(c.t)}</h3>${list(c.items)}</div>`).join('')}</div></section>`;break;
case'splitmetric':h=`<section class="splitmetric"><div class="panel"><div class="num">${esc(s.left.num)}</div><h3>${esc(s.left.t)}</h3>${list(s.left.items)}</div><div class="panel"><div class="num">${esc(s.right.num)}</div><h3>${esc(s.right.t)}</h3>${list(s.right.items)}</div><div class="badgewide">${esc(s.badge)}</div></section>`;break;
case'flow':h=`<section class="flow">${(s.nodes||[]).map((n,i)=>`${i?'<div class="arrow"><i class="fa-solid fa-arrow-right"></i></div>':''}<div class="node">${esc(n)}</div>`).join('')}<div class="flowfoot">${esc(s.footer)}</div></section>`;break;
case'chain':h=`<section class="chain">${(s.chain||[]).map(x=>`<div class="chaincard">${icon(x.i)}<h3>${esc(x.t)}</h3><p>${esc(x.d)}</p></div>`).join('')}</section>`;break;
case'metriccards':h=`<section class="metriccards">${(s.metrics||[]).map(x=>`<div class="metric"><strong>${esc(x.v)}</strong><h3>${esc(x.t)}</h3><p>${esc(x.d)}</p></div>`).join('')}</section>`;break;
case'actionplan':h=`<section class="actions">${(s.actions||[]).map(x=>`<div class="action"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</section>`;break;
case'end':h=`<section class="end"><i class="fa-solid fa-shield-heart"></i><h2 class="mega">${esc(s.title)}</h2><div class="sub">${esc(s.subtitle)}</div><div class="contact">${esc(s.contact)}</div></section>`;break;
default:h='<div class="error">Slide não suportado.</div>'}
return `<div class="slide">${h}</div>`}
function clamp(i){return Math.max(0,Math.min(slides.length-1,Number(i)||0))}
function render(){if(!slides.length)return;current=clamp(current);const s=slides[current];$('head').classList.toggle('hidden',['cover','end'].includes(s.type));$('slideTitle').textContent=s.title||'FUNFARM';$('slideIcon').innerHTML=icon(s.icon);$('stage').innerHTML=renderSlide(s);$('progress').style.width=`${((current+1)/slides.length)*100}%`;$('counter').textContent=`SLIDE ${current+1} / ${slides.length}`;document.title=`${s.title||'FUNFARM'} • Apresentação`}
async function go(i){current=clamp(i);render();try{if(db)await db.ref(`${base}/state`).update({currentSlide:current,updatedAt:firebase.database.ServerValue.TIMESTAMP})}catch(e){console.warn(e)}}
async function init(){render();try{firebase.initializeApp(window.FUNFARM_FIREBASE_CONFIG);const auth=firebase.auth();await auth.signInAnonymously();db=firebase.database();const snap=await db.ref(`${base}/state/currentSlide`).once('value');if(snap.exists()){current=clamp(snap.val());render()}db.ref(`${base}/state/currentSlide`).on('value',s=>{if(s.exists()){const n=clamp(s.val());if(n!==current){current=n;render()}}});db.ref(`${base}/action`).on('value',s=>{const a=s.val()||{};if(a.type==='HOME'&&a.ts)go(0)})}catch(e){console.error(e)}}
$('prev').onclick=()=>go(current-1);$('next').onclick=()=>go(current+1);$('home').onclick=()=>go(0);$('fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){}};window.addEventListener('keydown',e=>{if(['ArrowRight','PageDown','ArrowDown'].includes(e.key)){e.preventDefault();go(current+1)}if(['ArrowLeft','PageUp','ArrowUp','Backspace'].includes(e.key)){e.preventDefault();go(current-1)}if(e.key.toLowerCase()==='f')$('fullscreen').click()});let tx=null;$('stage').addEventListener('touchstart',e=>tx=e.changedTouches[0]?.clientX??null,{passive:true});$('stage').addEventListener('touchend',e=>{if(tx===null)return;const dx=(e.changedTouches[0]?.clientX??tx)-tx;tx=null;if(Math.abs(dx)>70)go(current+(dx<0?1:-1))},{passive:true});init();
})();
